import { type ReactNode } from 'react'
import '@/styles/globals.css'

import { Inter } from 'next/font/google'
import { Providers } from './providers'
import clsx from 'clsx'
import { type Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: './favicon.svg'
  }
}

const inter = Inter({
  subsets: ['latin']
})

export default function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(inter.className, 'dark:bg-gray-900')}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
